# Generated by Django 4.2.27 on 2026-02-05 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_user_user_type_coursecategory_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='jobs.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('pdf_notes', models.FileField(blank=True, null=True, upload_to='lesson_notes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('duration', models.CharField(help_text='e.g. 15 mins', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='jobs.coursemodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
